services:
  mysql:
    image: mysql:8.0
    container_name: matrimonial_app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: matrimonial_app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./matrimonial_app.sql:/docker-entrypoint-initdb.d/matrimonial_app.sql

volumes:
  mysql_data:
